spring.application.name=api-gateway
server.port=9090

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Auto discover and route to services registered in Eureka
spring.cloud.gateway.discovery.locator.enabled=true

# Use lowercase service names in URL
# Access via: http://localhost:9090/greet-service/greet
spring.cloud.gateway.discovery.locator.lower-case-service-id=true